### ISSUE TITLE
DZ-3 DIMITRIEV

### ISSUE THREAD

**Issue by NikolayDimitriev** [MIEE-ACS/domashnee-zadanie-no3-NikolayDimitriev#1]

**Comment by d-makarenko** [comment]
Два замечания:
1. Неправильно работает подсчет слов содержащих дефис: кто-нибудь, кто-то и тд.
2. Программа скопирована у Смородинова (или наоборот, но он сдал первым)

**Comment by NikolayDimitriev** [comment]
1. Совсем забыл, можно добавить (... || t=='-') к условию. Теперь считает.
2. Идея была общей.
Ну это, что бы не было confused emoji :)
